WIP: Feature/wysiwyg editors
dmstr/yii2-json-editor pull request #37
Opened 2024-04-29 13:22 UTC by germanbisurgi

Alternatives for CKEditor: Jodit and SCEditor
Markdown editor: simpleMDE

2024-04-30 10:41 UTC, germanbisurgi commented
![editors-configs](https://github.com/dmstr/yii2-json-editor/assets/13135260/efd91b66-662f-4e8f-93b3-5048b5fc087f)

2024-04-30 10:51 UTC, eluhr requested changes

2024-04-30 10:51 UTC, eluhr commented on src/JoditAsset.php
> +    public $sourcePath = '@dmstr/jsoneditor/assets/';
Use @dmstr/jsoneditor/assets/jodit here to prevent publishing unwanted files

2024-04-30 10:51 UTC, eluhr commented on src/JoditAsset.php
> +    public $sourcePath = '@dmstr/jsoneditor/assets/';
Or why do we not use the files in  `/assets/jodit`

2024-04-30 10:51 UTC, eluhr commented on src/SceditorAsset.php
> +    public $sourcePath = '@dmstr/jsoneditor/assets/sceditor/minified';
why do we not use the files in /assets/sceditor/minified?

2024-04-30 10:51 UTC, eluhr commented on src/JsonEditorWidget.php
> +            $json = Yii::$app->settings->getOrSet('jodit.config', $joditConfig, 'jsoneditor', 'object');
Settings should be optional - see: https://github.com/dmstr/yii2-json-editor/pull/13

2024-04-30 10:51 UTC, eluhr commented
Why are the assets bundles not in the `assets` directory?

2024-05-06 07:54 UTC, germanbisurgi commented
Ping

2024-05-06 08:05 UTC, eluhr approved these changes
LGTM

2024-05-06 10:26 UTC, schmunk42 requested changes
Please include the LICENSE files and a note in the README about the bundled assets.

2024-05-07 11:41 UTC, schmunk42 approved these changes

2024-05-15 08:01 UTC, germanbisurgi commented
This pull request is no longer WIP. Should i merge and tag?

2024-05-15 08:07 UTC, schmunk42 commented
Yes, go ahead.

2024-05-15 08:10 UTC, merged